spring.application.name=videostreaming-backend
spring.datasource.url=jdbc:mysql://localhost:3306/videostream_db
spring.datasource.username=root
spring.datasource.password=root@admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##OAuth client 2
spring.security.oauth2.client.registration.google.client-id=90002626695-df4d8mc78ptl1dtfthtg5c0t40stenmj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo